# Generated by Django 5.1.3 on 2024-11-15 14:51

import core.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="cid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                length=16,
                max_length=40,
                prefix="catid_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234", length=16, max_length=40, prefix="", unique=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234",
                length=16,
                max_length=40,
                prefix="venid_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="images",
            field=models.ImageField(upload_to="product_images"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(default="123, mainstreet london", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact",
            field=models.CharField(default="+123 (456) 789", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="image",
            field=models.ImageField(upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
