# Generated by Django 5.1.3 on 2024-11-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_vendor_image_remove_vendor_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact",
            field=models.CharField(max_length=100),
        ),
    ]
