# Generated by Django 5.1.3 on 2024-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_vendor_address_alter_vendor_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=12),
        ),
    ]
